services:
  - type: web
    name: guide-conception-cnsmdp
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
